// Code generated by goyacc -p yaccDate -o yaccDate.go yaccDate.y. DO NOT EDIT.

//line yaccDate.y:12

package yaccDate

import __yyfmt__ "fmt"

//line yaccDate.y:15

import (
	"bufio"
	"fmt"
	"github.com/tkuchiki/go-timezone"
	"log"
	"os"
	"strconv"
	"strings"
	"time"
	"unicode"
)

type timeDateInfo struct {
	arr [7]int
	tz  string
	off bool // true if offset to be used, overrides tz
}

//line yaccDate.y:36
type yaccDateSymType struct {
	yys int
	// 0 - sec
	// 1 - min
	// 2 - hour
	// 3 - day
	// 4 - month
	// 5 - year
	// 6 - timezone offset (seconds)
	ival int
	tdi  timeDateInfo
}

const NUM2 = 57346
const NUM4 = 57347
const WEEKDAY = 57348
const MONTH = 57349
const TIMEZONE = 57350
const UNKNOWN = 57351

var yaccDateToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUM2",
	"NUM4",
	"WEEKDAY",
	"MONTH",
	"TIMEZONE",
	"'+'",
	"'-'",
	"':'",
	"'('",
	"')'",
	"UNKNOWN",
}

var yaccDateStatenames = [...]string{}

const yaccDateEofCode = 1
const yaccDateErrCode = 2
const yaccDateInitialStackSize = 16

//line yaccDate.y:149

var weekDays = map[string]int{
	"sun": 0,
	"mon": 1,
	"tue": 2,
	"wed": 3,
	"thu": 4,
	"fri": 5,
	"sat": 6,
	// Add more week days as needed
}

var monthNames = map[string]time.Month{
	"jan": time.January,
	"feb": time.February,
	"mar": time.March,
	"apr": time.April,
	"may": time.May,
	"jun": time.June,
	"jul": time.July,
	"aug": time.August,
	"sep": time.September,
	"oct": time.October,
	"nov": time.November,
	"dec": time.December,
	// Add more month names as needed
}

type Lexer struct {
	result  timeDateInfo
	scanner *bufio.Scanner
	tz      *timezone.Timezone
}

func NewLexer(input string) *Lexer {
	scanner := bufio.NewScanner(strings.NewReader(input))
	tz := timezone.New()
	scanner.Split(customSplit)
	return &Lexer{scanner: scanner, tz: tz}
}

func customSplit(data []byte, atEOF bool) (advance int, token []byte, err error) {
	// Skip leading spaces or commas.
	start := 0
	for ; start < len(data); start++ {
		if !unicode.IsSpace(rune(data[start])) && data[start] != ',' {
			break
		}
	}
	// Scan until space, comma, or symbol, marking end of word.
	// If we see a letter, consume as a symbol.
	if start >= len(data) {
		// Request more data.
		return start, nil, nil
	}
	if unicode.IsLetter(rune(data[start])) {
		for j := start + 1; j < len(data); j++ {
			if !unicode.IsLetter(rune(data[j])) {
				//fmt.Println(j, data[start:j],)
				return j, data[start:j], nil
			}
		}
	} else if unicode.IsDigit(rune(data[start])) {
		// If we see a digit, consume as a number.
		for j := start + 1; j < len(data); j++ {
			if !unicode.IsDigit(rune(data[j])) {
				//fmt.Println(j, data[start:j],)
				return j, data[start:j], nil
			}
		}
	} else {
		// Otherwise, consume as a single rune.
		//fmt.Println(start + 1, data[start])
		return start + 1, data[start : start+1], nil
	}
	// Return the remaining bytes if we're at EOF.
	if atEOF && len(data) > start {
		return len(data), data[start:], nil
	}

	// Request more data.
	return start, nil, nil
}

func (l *Lexer) Lex(lval *yaccDateSymType) int {
	var err error
	if !l.scanner.Scan() {
		return 0
	}
	token := l.scanner.Text()
	le := len(token)

	// Check for one or two digit integer numbers
	if le <= 2 && unicode.IsDigit(rune(token[0])) && (le == 1 || unicode.IsDigit(rune(token[1]))) {
		lval.ival, err = strconv.Atoi(token)
		if err != nil {
			return UNKNOWN
		}
		return NUM2
	}

	// Check for four digit integers
	if len(token) == 4 && unicode.IsDigit(rune(token[0])) && unicode.IsDigit(rune(token[1])) && unicode.IsDigit(rune(token[2])) && unicode.IsDigit(rune(token[3])) {
		lval.ival, err = strconv.Atoi(token)
		if err != nil {
			return UNKNOWN
		}
		return NUM4
	}

	// Check for week days
	if day, ok := weekDays[strings.ToLower(token)]; ok {
		lval.ival = day
		return WEEKDAY
	}

	// Check for month names
	if month, ok := monthNames[strings.ToLower(token)]; ok {
		lval.ival = int(month)
		return MONTH
	}

	// Check for time zones
	// we don't calculate it ourselves because its offset may depend on the date (daylight saving time)
	tzAbbrInfos, _ := l.tz.GetTzAbbreviationInfo(strings.ToUpper(token))
	if len(tzAbbrInfos) > 0 {
		lval.tdi.tz = strings.ToUpper(token)
		//fmt.Println("TZ: ", token)
		return TIMEZONE
	}

	// Return other symbols as individual tokens
	if len(token) == 1 {
		switch r := rune(token[0]); r {
		case '+', '-', ':', '(', ')':
			return int(r)
		default:
			//
		}
	}
	//fmt.Println("No TZ: ", token)
	return UNKNOWN
}

func (l *Lexer) Error(e string) {
	fmt.Printf("Error: %s\n", e)
}

func FlexDateToTime(dateStr string) time.Time {
	var myZone *time.Location
	lexer := NewLexer(dateStr)
	if yaccDateParse(lexer) == 1 {
		log.Fatal("Cannot parse date:", dateStr)
		os.Exit(1)
	}
	if lexer.result.tz != "" {
		myZone = time.FixedZone(lexer.result.tz, 0)
	} else {
		myZone = time.FixedZone("UTC", lexer.result.arr[6])
	}
	return time.Date(lexer.result.arr[5], time.Month(lexer.result.arr[4]), lexer.result.arr[3], lexer.result.arr[2], lexer.result.arr[1], lexer.result.arr[0], 0, myZone)
}

//line yacctab:1
var yaccDateExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yaccDatePrivate = 57344

const yaccDateLast = 52

var yaccDateAct = [...]int8{
	33, 23, 13, 16, 17, 36, 14, 13, 11, 25,
	12, 14, 24, 42, 37, 22, 28, 31, 16, 17,
	40, 27, 26, 25, 32, 9, 24, 6, 34, 35,
	29, 30, 5, 45, 41, 39, 21, 18, 9, 4,
	10, 43, 15, 20, 38, 44, 8, 19, 7, 3,
	2, 1,
}

var yaccDatePact = [...]int16{
	21, -1000, -1000, -6, 34, -1000, -1000, 32, 5, -1000,
	-1000, 9, -1, -1000, 8, 26, -1000, -1000, -1000, -1000,
	6, -1000, 19, 24, -1000, -1000, -1000, -1000, -8, 3,
	-1000, 31, 10, -1000, -1000, -1000, -1000, 30, 2, -1000,
	24, -1000, 29, -1000, -1000, -1000,
}

var yaccDatePgo = [...]int8{
	0, 51, 50, 49, 32, 48, 47, 8, 0, 1,
	46, 45, 44, 43, 42, 10, 40, 39,
}

var yaccDateR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 3, 4, 7, 7,
	16, 16, 16, 15, 15, 15, 14, 14, 17, 6,
	13, 12, 11, 5, 5, 10, 9, 9, 8, 8,
}

var yaccDateR2 = [...]int8{
	0, 1, 2, 2, 1, 2, 1, 2, 1, 3,
	1, 2, 2, 2, 2, 4, 1, 1, 1, 5,
	1, 1, 1, 5, 3, 1, 1, 1, 1, 1,
}

var yaccDateChk = [...]int16{
	-1000, -1, -2, -3, -17, -4, 6, -5, -10, 4,
	-16, -7, -15, 8, 12, -14, 9, 10, -4, -6,
	-13, 4, 10, -9, 7, 4, -15, -7, 8, 4,
	5, 11, -9, -8, 4, 5, 13, 11, -12, 4,
	10, 4, 11, -8, -11, 4,
}

var yaccDateDef = [...]int8{
	0, -2, 1, 4, 0, 6, 18, 0, 0, 25,
	2, 3, 10, 8, 0, 0, 16, 17, 5, 7,
	0, 20, 0, 0, 26, 27, 11, 12, 0, 13,
	14, 0, 0, 24, 28, 29, 9, 0, 0, 21,
	0, 15, 0, 23, 19, 22,
}

var yaccDateTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	12, 13, 3, 9, 3, 10, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 11,
}

var yaccDateTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 14,
}

var yaccDateTok3 = [...]int8{
	0,
}

var yaccDateErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yaccDateDebug        = 0
	yaccDateErrorVerbose = false
)

type yaccDateLexer interface {
	Lex(lval *yaccDateSymType) int
	Error(s string)
}

type yaccDateParser interface {
	Parse(yaccDateLexer) int
	Lookahead() int
}

type yaccDateParserImpl struct {
	lval  yaccDateSymType
	stack [yaccDateInitialStackSize]yaccDateSymType
	char  int
}

func (p *yaccDateParserImpl) Lookahead() int {
	return p.char
}

func yaccDateNewParser() yaccDateParser {
	return &yaccDateParserImpl{}
}

const yaccDateFlag = -1000

func yaccDateTokname(c int) string {
	if c >= 1 && c-1 < len(yaccDateToknames) {
		if yaccDateToknames[c-1] != "" {
			return yaccDateToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yaccDateStatname(s int) string {
	if s >= 0 && s < len(yaccDateStatenames) {
		if yaccDateStatenames[s] != "" {
			return yaccDateStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yaccDateErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yaccDateErrorVerbose {
		return "syntax error"
	}

	for _, e := range yaccDateErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yaccDateTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yaccDatePact[state])
	for tok := TOKSTART; tok-1 < len(yaccDateToknames); tok++ {
		if n := base + tok; n >= 0 && n < yaccDateLast && int(yaccDateChk[int(yaccDateAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yaccDateDef[state] == -2 {
		i := 0
		for yaccDateExca[i] != -1 || int(yaccDateExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yaccDateExca[i] >= 0; i += 2 {
			tok := int(yaccDateExca[i])
			if tok < TOKSTART || yaccDateExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yaccDateExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yaccDateTokname(tok)
	}
	return res
}

func yaccDatelex1(lex yaccDateLexer, lval *yaccDateSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yaccDateTok1[0])
		goto out
	}
	if char < len(yaccDateTok1) {
		token = int(yaccDateTok1[char])
		goto out
	}
	if char >= yaccDatePrivate {
		if char < yaccDatePrivate+len(yaccDateTok2) {
			token = int(yaccDateTok2[char-yaccDatePrivate])
			goto out
		}
	}
	for i := 0; i < len(yaccDateTok3); i += 2 {
		token = int(yaccDateTok3[i+0])
		if token == char {
			token = int(yaccDateTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yaccDateTok2[1]) /* unknown char */
	}
	if yaccDateDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yaccDateTokname(token), uint(char))
	}
	return char, token
}

func yaccDateParse(yaccDatelex yaccDateLexer) int {
	return yaccDateNewParser().Parse(yaccDatelex)
}

func (yaccDatercvr *yaccDateParserImpl) Parse(yaccDatelex yaccDateLexer) int {
	var yaccDaten int
	var yaccDateVAL yaccDateSymType
	var yaccDateDollar []yaccDateSymType
	_ = yaccDateDollar // silence set and not used
	yaccDateS := yaccDatercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yaccDatestate := 0
	yaccDatercvr.char = -1
	yaccDatetoken := -1 // yaccDatercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yaccDatestate = -1
		yaccDatercvr.char = -1
		yaccDatetoken = -1
	}()
	yaccDatep := -1
	goto yaccDatestack

ret0:
	return 0

ret1:
	return 1

yaccDatestack:
	/* put a state and value onto the stack */
	if yaccDateDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yaccDateTokname(yaccDatetoken), yaccDateStatname(yaccDatestate))
	}

	yaccDatep++
	if yaccDatep >= len(yaccDateS) {
		nyys := make([]yaccDateSymType, len(yaccDateS)*2)
		copy(nyys, yaccDateS)
		yaccDateS = nyys
	}
	yaccDateS[yaccDatep] = yaccDateVAL
	yaccDateS[yaccDatep].yys = yaccDatestate

yaccDatenewstate:
	yaccDaten = int(yaccDatePact[yaccDatestate])
	if yaccDaten <= yaccDateFlag {
		goto yaccDatedefault /* simple state */
	}
	if yaccDatercvr.char < 0 {
		yaccDatercvr.char, yaccDatetoken = yaccDatelex1(yaccDatelex, &yaccDatercvr.lval)
	}
	yaccDaten += yaccDatetoken
	if yaccDaten < 0 || yaccDaten >= yaccDateLast {
		goto yaccDatedefault
	}
	yaccDaten = int(yaccDateAct[yaccDaten])
	if int(yaccDateChk[yaccDaten]) == yaccDatetoken { /* valid shift */
		yaccDatercvr.char = -1
		yaccDatetoken = -1
		yaccDateVAL = yaccDatercvr.lval
		yaccDatestate = yaccDaten
		if Errflag > 0 {
			Errflag--
		}
		goto yaccDatestack
	}

yaccDatedefault:
	/* default state action */
	yaccDaten = int(yaccDateDef[yaccDatestate])
	if yaccDaten == -2 {
		if yaccDatercvr.char < 0 {
			yaccDatercvr.char, yaccDatetoken = yaccDatelex1(yaccDatelex, &yaccDatercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yaccDateExca[xi+0] == -1 && int(yaccDateExca[xi+1]) == yaccDatestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yaccDaten = int(yaccDateExca[xi+0])
			if yaccDaten < 0 || yaccDaten == yaccDatetoken {
				break
			}
		}
		yaccDaten = int(yaccDateExca[xi+1])
		if yaccDaten < 0 {
			goto ret0
		}
	}
	if yaccDaten == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yaccDatelex.Error(yaccDateErrorMessage(yaccDatestate, yaccDatetoken))
			Nerrs++
			if yaccDateDebug >= 1 {
				__yyfmt__.Printf("%s", yaccDateStatname(yaccDatestate))
				__yyfmt__.Printf(" saw %s\n", yaccDateTokname(yaccDatetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yaccDatep >= 0 {
				yaccDaten = int(yaccDatePact[yaccDateS[yaccDatep].yys]) + yaccDateErrCode
				if yaccDaten >= 0 && yaccDaten < yaccDateLast {
					yaccDatestate = int(yaccDateAct[yaccDaten]) /* simulate a shift of "error" */
					if int(yaccDateChk[yaccDatestate]) == yaccDateErrCode {
						goto yaccDatestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yaccDateDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yaccDateS[yaccDatep].yys)
				}
				yaccDatep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yaccDateDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yaccDateTokname(yaccDatetoken))
			}
			if yaccDatetoken == yaccDateEofCode {
				goto ret1
			}
			yaccDatercvr.char = -1
			yaccDatetoken = -1
			goto yaccDatenewstate /* try again in the same state */
		}
	}

	/* reduction by production yaccDaten */
	if yaccDateDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yaccDaten, yaccDateStatname(yaccDatestate))
	}

	yaccDatent := yaccDaten
	yaccDatept := yaccDatep
	_ = yaccDatept // guard against "declared and not used"

	yaccDatep -= int(yaccDateR2[yaccDaten])
	// yaccDatep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yaccDatep+1 >= len(yaccDateS) {
		nyys := make([]yaccDateSymType, len(yaccDateS)*2)
		copy(nyys, yaccDateS)
		yaccDateS = nyys
	}
	yaccDateVAL = yaccDateS[yaccDatep+1]

	/* consult goto table to find next state */
	yaccDaten = int(yaccDateR1[yaccDaten])
	yaccDateg := int(yaccDatePgo[yaccDaten])
	yaccDatej := yaccDateg + yaccDateS[yaccDatep].yys + 1

	if yaccDatej >= yaccDateLast {
		yaccDatestate = int(yaccDateAct[yaccDateg])
	} else {
		yaccDatestate = int(yaccDateAct[yaccDatej])
		if int(yaccDateChk[yaccDatestate]) != -yaccDaten {
			yaccDatestate = int(yaccDateAct[yaccDateg])
		}
	}
	// dummy call; replaced with literal code
	switch yaccDatent {

	case 1:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:57
		{
			yaccDatelex.(*Lexer).result = yaccDateVAL.tdi
		}
	case 2:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:63
		{
			yaccDateVAL.tdi = yaccDateDollar[1].tdi
			yaccDateVAL.tdi.arr[6] = yaccDateDollar[2].ival
		}
	case 3:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:68
		{
			yaccDateVAL.tdi = yaccDateDollar[1].tdi
			yaccDateVAL.tdi.tz = yaccDateDollar[2].tdi.tz
		}
	case 4:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:72
		{
			yaccDateVAL.tdi = yaccDateDollar[1].tdi
		}
	case 5:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:75
		{
			yaccDateVAL.tdi = yaccDateDollar[2].tdi
		}
	case 6:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:76
		{
			yaccDateVAL.tdi = yaccDateDollar[1].tdi
		}
	case 7:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:80
		{
			yaccDateVAL.tdi.arr[0] = yaccDateDollar[2].tdi.arr[0]
			yaccDateVAL.tdi.arr[1] = yaccDateDollar[2].tdi.arr[1]
			yaccDateVAL.tdi.arr[2] = yaccDateDollar[2].tdi.arr[2]
			yaccDateVAL.tdi.arr[3] = yaccDateDollar[1].tdi.arr[3]
			yaccDateVAL.tdi.arr[4] = yaccDateDollar[1].tdi.arr[4]
			yaccDateVAL.tdi.arr[5] = yaccDateDollar[1].tdi.arr[5]
		}
	case 8:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:90
		{
			yaccDateVAL.tdi = yaccDateDollar[1].tdi
		}
	case 9:
		yaccDateDollar = yaccDateS[yaccDatept-3 : yaccDatept+1]
//line yaccDate.y:91
		{
			yaccDateVAL.tdi = yaccDateDollar[2].tdi
		}
	case 10:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:95
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 11:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:96
		{
			yaccDateVAL.ival = yaccDateDollar[2].ival
		}
	case 12:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:97
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 13:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:100
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival * yaccDateDollar[2].ival * 3600
		}
	case 14:
		yaccDateDollar = yaccDateS[yaccDatept-2 : yaccDatept+1]
//line yaccDate.y:101
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival*((yaccDateDollar[2].ival/100)*3600) + (yaccDateDollar[2].ival%100)*60
		}
	case 15:
		yaccDateDollar = yaccDateS[yaccDatept-4 : yaccDatept+1]
//line yaccDate.y:102
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival * (yaccDateDollar[2].ival*3600 + yaccDateDollar[4].ival*60)
		}
	case 16:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:105
		{
			yaccDateVAL.ival = 1
		}
	case 17:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:106
		{
			yaccDateVAL.ival = -1
		}
	case 19:
		yaccDateDollar = yaccDateS[yaccDatept-5 : yaccDatept+1]
//line yaccDate.y:113
		{
			yaccDateVAL.tdi.arr[0] = yaccDateDollar[5].ival
			yaccDateVAL.tdi.arr[1] = yaccDateDollar[3].ival
			yaccDateVAL.tdi.arr[2] = yaccDateDollar[1].ival
		}
	case 20:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:120
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 21:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:121
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 22:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:122
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 23:
		yaccDateDollar = yaccDateS[yaccDatept-5 : yaccDatept+1]
//line yaccDate.y:126
		{
			yaccDateVAL.tdi.arr[5] = yaccDateDollar[5].ival
			yaccDateVAL.tdi.arr[4] = yaccDateDollar[3].ival
			yaccDateVAL.tdi.arr[3] = yaccDateDollar[1].ival
		}
	case 24:
		yaccDateDollar = yaccDateS[yaccDatept-3 : yaccDatept+1]
//line yaccDate.y:132
		{
			yaccDateVAL.tdi.arr[5] = yaccDateDollar[3].ival
			yaccDateVAL.tdi.arr[4] = yaccDateDollar[2].ival
			yaccDateVAL.tdi.arr[3] = yaccDateDollar[1].ival
		}
	case 25:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:139
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 26:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:142
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 27:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:143
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 28:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:146
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	case 29:
		yaccDateDollar = yaccDateS[yaccDatept-1 : yaccDatept+1]
//line yaccDate.y:147
		{
			yaccDateVAL.ival = yaccDateDollar[1].ival
		}
	}
	goto yaccDatestack /* stack new state and value */
}
